### PR TITLE
refactor: remove usage of defaultdict

### PR DESCRIPTION
**Pull request by henryiii**
Using defaultdict is somewhat discouraged since it is really easy to hide what is happening. I've switched to using `.setdefault` and `.get`, which are explicit and don't require a special import or custom dict.

----
📚 Documentation preview 📚: https://dependency-groups--5.org.readthedocs.build/en/5/

### CODE REVIEW

**Comment by sirosen** [comment]
I don't mind this change at all -- both idioms read fine to me -- but we've got a mypy error. I'll try to make time later today to see what's up with that. I'm guessing that one of those defaultdicts was giving some type information which we now need in an annotation.

**Comment by henryiii** [comment]
I can check it in a few minutes.

**Comment by henryiii** [comment]
Yes, I think it was getting `list[Any]` before, due to the item in the defaultdict constructor. I would have expected it to still complain before, since it shouldn't infer the Any, but it didn't.

**Comment by sirosen** [comment]
Thanks for the quick fix; onto the other PRs! :smile:

**Pull request merged**
